spring:
  application:
    name: claim-request-service

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/claim_db?useSSL=false&allowPublicKeyRetrieval=true
    username: claimuser
    password: claimpwd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
